### ISSUE TITLE
resolution changing for mac-2

### ISSUE THREAD

**Issue by marcusramberg** [aws-samples/amazon-ec2-mac-getting-started#6]
Hi, your guides recommend displayplacer for changing resolution on ec2 macs, but this doesn't seem to work for arm macs? After installing from brew I see 

```
displayplacer
zsh: bad CPU type in executable: displayplacer
```
Do you have a different recommendation for doing this on arm macs?

**Comment by thimslugga** [comment]
> Hi, your guides recommend displayplacer for changing resolution on ec2 macs, but this doesn't seem to work for arm macs? After installing from brew I see 
> 
> 
> 
> ```
> 
> displayplacer
> 
> zsh: bad CPU type in executable: displayplacer
> 
> ```
> 
> Do you have a different recommendation for doing this on arm macs?

You're correct, displayplacer does not support Apple Silicon based Mac hardware. For mac2.metal, you can use [BetterDisplay](https://github.com/waydabber/BetterDisplay) to adjust the display resolution.
